name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"

jobs:
  release:
    permissions: write-all
    name: 🔖 release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Creates a release in GitHub and uploads attachments
        run: gh release create ${{ github.ref_name }}  -F CHANGELOG.md ./build.txt
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
